import { readFileSync } from 'fs';

import alias from '@rollup/plugin-alias';
import { babel } from '@rollup/plugin-babel';
import commonjs from '@rollup/plugin-commonjs';
import json from '@rollup/plugin-json';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import replace from '@rollup/plugin-replace';
import { string } from 'rollup-plugin-string';
import virtual from '@rollup/plugin-virtual';

export default {
  input: 'build/scripts/test-inputs.js', // Input file generated by gulp task
  output: {
    file: 'build/scripts/tests.bundle.js',
    format: 'es',
    sourcemap: true,
  },
  treeshake: false,
  plugins: [
    // Replace some problematic dependencies which are imported but not actually
    // used with stubs. Per @rollup/plugin-virtual's docs, this must be listed
    // first.
    virtual({
      // Node modules that are not available in the browser.
      crypto: '',
      util: '',
    }),
    alias({
      entries: [
        {
          find: 'enzyme',
          replacement: 'ureact/enzyme',
        },
        {
          find: 'preact',
          replacement: 'ureact',
        },
      ],
    }),
    replace({
      preventAssignment: true,
      values: {
        'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV),
        __VERSION__: JSON.parse(readFileSync('./package.json').toString())
          .version,
      },
    }),
    nodeResolve({
      browser: true,

      // Disallow use of browser polyfills for Node builtin modules. We're
      // trying to avoid dependencies which rely on these.
      //
      // There are a couple of references to Node builtins that are stubbed by
      // configuration for the `virtual` plugin above.
      preferBuiltins: false,
    }),
    commonjs({
      include: ['node_modules/**', '.yalc/**'],
    }),
    string({
      include: '**/*.{html,svg}',
    }),
    json(),

    // The Babel transform generates additional code for code coverage.
    // Place it last to minimize amount of code parsed by subsequent plugins.
    babel({
      babelHelpers: 'bundled',
      exclude: 'node_modules/**',
      presets: [
        [
          '@babel/preset-react',
          {
            // Turn off the `development` setting in tests to prevent warnings
            // about `this`. See https://github.com/babel/babel/issues/9149.
            development: false,
            runtime: 'automatic',
            importSource: 'ureact',
          },
        ],
      ],
      plugins: [
        'mockable-imports',
        [
          'babel-plugin-istanbul',
          {
            exclude: ['**/test/**/*.js', '**/test-util/**'],
          },
        ],
      ],
    }),
  ],
};
